export const GET_POSTS = 'GET_POSTS';
export const GET_USER_POSTS = 'GET_USER_POSTS';
export const GET_POSTS_INFO = 'GET_POSTS_INFO';
export const GET_POSTS_COMMENTS = 'GET_POSTS_COMMENTS';
export const GET_POSTS_REACTION = 'GET_POSTS_REACTION';
