export const GET_RESIDENTS_LIST = 'GET_RESIDENTS_LIST';
export const GET_RESIDENTS_ISSUCCESS = 'GET_RESIDENTS_ISSUCCESS';
export const GET_RESIDENTS_FAD_DATA = 'GET_RESIDENTS_FAD_DATA';
export const GET_FORGOT_PASSWORD_PROMISE = 'GET_FORGOT_PASSWORD_PROMISE';
export const GET_MEMBERS = 'GET_MEMBERS';
